site_name: Krews
repo_name: krews
repo_url: https://github.com/weng-lab/krews
site_description: "Kotlin Reactive Workflows"
site_author: Jason Brooks
remote_branch: master

copyright: 'Copyright &copy; 2018 Weng Lab'

theme:
  name: 'material'
  logo: img/krews_logo_white.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue grey'
    accent: 'amber'

extra_css:
  - 'css/extra.css'

markdown_extensions:
  - admonition
  - meta
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

nav:
  - 'Why Krews?':
      - 'Tooling': why_krews.md
      - 'Clean, Concise, and Powerful': why_krews/#clean-concise-powerful
      - 'Docker Native': why_krews/#docker-native
      - 'Cloud Native': why_krews/#cloud-native
  - 'Quick Start':
      - 'Creating a Project': quickstart.md
      - 'Installing Krews Dependency': quickstart/#installing-krews-dependency
      - 'Building': quickstart/#building
  - 'Docker':
      - 'How Krews uses Docker': docker.md
      - 'What about Singularity': docker/#what-about-singularity
  - 'Reactor':
      - 'Publishers, Fluxes, and Monos': reactor.md
      - 'Flux and Mono Creation': reactor/#flux-and-mono-creation
      - 'Operations': reactor/#operations
  - 'Workflows':
      - 'Workflow Basics': workflows.md
      - 'Tasks': workflows/#tasks
      - 'Files': workflows/#files
      - 'Parameters': workflows/#params
      - 'Code Organization': workflows/#code-organization
  - 'Execution Environments':
      - 'Google': execution_environments.md
      - 'Slurm': execution_environments/#slurm
      - 'Local Docker': execution_environments/#local-docker
  - 'Configurations':
      - 'Configuration Basics': config.md
      - 'Workflow Configurations': config/#workflow-configurations
      - 'Task Configurations': config/#task-configurations
      - 'Parameters': config/#parameters
  - 'Output and State':
      - 'Caching': state.md
      - 'State': state/#state
      - 'Reports': state/#reports
      - 'Workflow Output Layout': state/#workflow-output-layout